[package]
name = "argparsh"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
pyo3 = { version = "0.22.2", features = ["auto-initialize"] }
serde_qs = "0.13.0"
